from django.urls import path
from . import views
# from .views import preguntas_cliente
from .views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView
from application.views import registrar_devolucion, responder_pregunta

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('verificar-email/<str:token>/',
         views.verificar_email, name='verificar_email'),
    path('verificar-codigo/', views.verificar_codigo, name='verificar_codigo'),
    path('perfil/', views.perfil, name='perfil'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/eliminar/', views.eliminar_perfil, name='eliminar_perfil'),
    path('permisos/agregar/', views.agregar_permiso, name='agregar_permiso'),
    path('permisos/eliminar/<int:permiso_id>/',
         views.eliminar_permiso, name='eliminar_permiso'),

    # Employee management
    path('empleados/registrar/', views.registrar_empleado,
         name='registrar_empleado'),
    path('empleados/', views.lista_empleados, name='lista_empleados'),
    path('empleados/eliminar/<int:empleado_id>/',
         views.eliminar_empleado, name='eliminar_empleado'),
    path('empleados/<int:empleado_id>/perfil/',
         views.ver_perfil_empleado, name='ver_perfil_empleado'),

    # Client management
    path('clientes/registrar/', views.registrar_cliente, name='registrar_cliente'),
    path('clientes/', views.lista_clientes, name='lista_clientes'),
    path('clientes/<int:cliente_id>/perfil/',
         views.ver_perfil_cliente, name='ver_perfil_cliente'),

    # Machinery management
    path('maquinaria/registrar/', views.registrar_maquinaria,
         name='registrar_maquinaria'),
    path('maquinaria/admin/', views.lista_maquinaria_admin, name='lista_maquinaria_admin'),
    path('maquinaria/editar/<int:maquina_id>/', views.editar_maquinaria, name='editar_maquinaria'),
    path('maquinaria/', views.lista_maquinaria, name='lista_maquinaria'),
    path('maquinaria/<int:maquina_id>/',
         views.detalle_maquinaria, name='detalle_maquinaria'),
    path('maquinaria/<int:maquina_id>/reservar/',
         views.reservar_maquinaria, name='reservar_maquinaria'),
    path('lista-maquinaria-admin/', views.lista_maquinaria_admin, name='lista_maquinaria_admin'),
    path('editar-maquinaria/<int:maquina_id>/', views.editar_maquinaria, name='editar_maquinaria'),
    path('eliminar-imagen/<int:imagen_id>/', views.eliminar_imagen, name='eliminar_imagen'),

    # Reservations
    path('reservas/historial/', views.historial_reservas,
         name='historial_reservas'),
    path('mis-reservas/', views.mis_reservas, name='mis_reservas'),
    path('reserva/<str:numero_reserva>/cancelar/',
         views.cancelar_reserva, name='cancelar_reserva'),
    path('reserva/<int:reserva_id>/pagar/',
         views.pagar_reserva, name='pagar_reserva'),
    path('reserva/<int:reserva_id>/procesar-pago/',
         views.procesar_pago, name='procesar_pago'),
    path('reserva/<int:reserva_id>/',
         views.detalle_reserva, name='detalle_reserva'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/failure/', views.payment_failure, name='payment_failure'),
    path('payment/pending/', views.payment_pending, name='payment_pending'),
    path('limpiar-datos/', views.limpiar_datos, name='limpiar_datos'),
    path('sobre-nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
    path('politicas-privacidad/', views.politicas_privacidad, name='politicas_privacidad'),
    path('ubicaciones/', views.lista_ubicaciones, name='lista_ubicaciones'),
    path('sucursales/', views.administrar_sucursales,
         name='administrar_sucursales'),
    path('sucursales/agregar/', views.agregar_sucursal, name='agregar_sucursal'),
    path('sucursales/<int:sucursal_id>/editar/',
         views.editar_sucursal, name='editar_sucursal'),
    path('sucursales/<int:sucursal_id>/eliminar/',
         views.eliminar_sucursal, name='eliminar_sucursal'),
    path('preguntas/', views.preguntas_cliente, name='preguntas_cliente'),
    path('preguntas/<int:pregunta_id>/editar/', views.editar_pregunta, name='editar_pregunta'),
    path('preguntas/<int:pregunta_id>/eliminar/', views.eliminar_pregunta, name='eliminar_pregunta'),
    path('preguntas/<int:pregunta_id>/responder/', responder_pregunta, name='responder_pregunta'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('gestionar-preguntas/', views.gestionar_preguntas, name='gestionar_preguntas'),
    path('registrar-devolucion/', registrar_devolucion, name='registrar_devolucion'),
    path('mis-alquileres/', views.mis_alquileres, name='mis_alquileres'),
    path('alquilar/', views.alquilar_maquinaria, name='alquilar_maquinaria'),
    path('alquilar/<int:id_maquina>/', views.alquilar_maquinaria_detalle, name='alquilar_maquinaria_detalle'),
    path('preguntas-frecuentes/', views.preguntas_frecuentes, name='preguntas_frecuentes'),
]
