# Generated by Django 5.2.1 on 2025-05-28 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='home_video/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video de inicio',
                'verbose_name_plural': 'Videos de inicio',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo_cancelacion', models.CharField(choices=[('total', 'Reembolso total (100%)'), ('parcial', 'Reembolso parcial (10-90%)'), ('sin_reembolso', 'Sin reembolso (0%)')], default='total', max_length=20)),
                ('politica_cancelacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo', models.CharField(choices=[('agricola', 'Agrícola'), ('construccion', 'Construcción'), ('mineria', 'Minería'), ('jardineria', 'Jardinería'), ('otros', 'Otros')], max_length=20)),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('permisos_requeridos', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('alquilado', 'Alquilado'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('stock', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='permisos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Formato permitido: JPG, PNG. Tamaño máximo: 5MB', upload_to='imagenes_maquinas/', verbose_name='Imagen')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='application.maquina')),
            ],
            options={
                'verbose_name': 'Imagen de maquinaria',
                'verbose_name_plural': 'Imágenes de maquinaria',
                'ordering': ['-es_principal', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('documento_foto', models.ImageField(blank=True, null=True, upload_to='documentos/')),
                ('email_verificado', models.BooleanField(default=False)),
                ('token_verificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('cuenta_bloqueada', models.BooleanField(default=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_verificacion_expira', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente_pago', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='application.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('motivo_fallo', models.CharField(blank=True, choices=[('tarjeta_invalida', 'Tarjeta inválida'), ('fondos_insuficientes', 'Fondos insuficientes'), ('error_conexion', 'Error de conexión con el banco'), ('otro', 'Otro error')], max_length=50, null=True)),
                ('numero_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='application.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimos_digitos', models.CharField(max_length=4)),
                ('tipo', models.CharField(max_length=20)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta de Crédito',
                'verbose_name_plural': 'Tarjetas de Crédito',
            },
        ),
    ]
