# Generated by Django 5.2.1 on 2025-06-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
