# Generated by Django 5.2.1 on 2025-05-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='politica_cancelacion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
    ]
