# Generated by Django 5.2.1 on 2025-05-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_maquina_descripcion'),
        ('application', '0002_remove_stock_field'),
    ]

    operations = [
    ]
