# Generated by Django 5.2.1 on 2025-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_maquina_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada'), ('devuelta', 'Devuelta')], default='pendiente_pago', max_length=20),
        ),
    ]
