# Generated by Django 5.2.1 on 2025-05-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_maquina_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='documento_foto',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='politica_cancelacion',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje (%) de cancelacion', max_digits=5),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ubicacion',
            field=models.CharField(max_length=255),
        ),
    ]
