# Generated by Django 5.2.1 on 2025-05-31 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_merge_20250531_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('dueno', 'Dueño')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.role'),
        ),
    ]
