# Generated by Django 5.2.1 on 2025-05-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_perfil_documento_foto_alter_maquina_anio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='home_video/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video de inicio',
                'verbose_name_plural': 'Videos de inicio',
            },
        ),
    ]
