# Generated by Django 5.2.1 on 2025-05-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_homevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='permisos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
