# Generated by Django 5.2.1 on 2025-06-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_perfil_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='token_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
