# Generated by Django 5.1.7 on 2025-05-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_permisoespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='tipo_cancelacion',
            field=models.CharField(choices=[('total', 'Reembolso total (100%)'), ('parcial', 'Reembolso parcial (10-90%)'), ('sin_reembolso', 'Sin reembolso (0%)')], default='total', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='politica_cancelacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje (%) de cancelacion', max_digits=5, null=True),
        ),
    ]
