# Generated by Django 5.2.1 on 2025-05-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_maquina_tipo_cancelacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_maquinas/')),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='application.maquina')),
            ],
            options={
                'verbose_name': 'Imagen de maquinaria',
                'verbose_name_plural': 'Imágenes de maquinaria',
            },
        ),
    ]
