# Generated by Django 5.2.1 on 2025-05-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_maquina_imagen_imagenmaquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='politica_cancelacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
