# Generated by Django 5.2.1 on 2025-05-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_maquina_politica_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
