# Generated by Django 3.2.8 on 2025-05-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20250524_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente_pago', max_length=20),
        ),
    ]
