# Generated by Django 3.2.8 on 2025-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='permisos_requeridos',
            field=models.TextField(blank=True, help_text='Deja en blanco si no se requieren permisos especiales', null=True),
        ),
    ]
