# Generated by Django 5.2.1 on 2025-06-19 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_pregunta_delete_preguntafrecuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='application.maquina'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('alquilado', 'Alquilado'), ('en_revision', 'En Revisión'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
