# Generated by Django 5.2.1 on 2025-06-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_pregunta_maquina_alter_maquina_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
