# Generated by Django 3.2.8 on 2025-05-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_maquina_permisos_requeridos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenmaquina',
            options={'ordering': ['-es_principal', '-fecha_subida'], 'verbose_name': 'Imagen de maquinaria', 'verbose_name_plural': 'Imágenes de maquinaria'},
        ),
        migrations.AlterField(
            model_name='imagenmaquina',
            name='es_principal',
            field=models.BooleanField(default=False, verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='imagenmaquina',
            name='imagen',
            field=models.ImageField(help_text='Formato permitido: JPG, PNG. Tamaño máximo: 5MB', upload_to='imagenes_maquinas/', verbose_name='Imagen'),
        ),
    ]
