# Generated by Django 5.2.1 on 2025-06-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_calificacion'),
        ('application', '0014_tarjetacredito_numero_tarjeta'),
    ]

    operations = [
    ]
