# Generated by Django 5.2.1 on 2025-05-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20250525_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cuenta_bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
