# Generated by Django 5.2.1 on 2025-06-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_merge_20250622_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_retiro',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
