# Generated by Django 5.2.1 on 2025-05-26 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_perfil_codigo_verificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='permisos_requeridos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('motivo_fallo', models.CharField(blank=True, choices=[('tarjeta_invalida', 'Tarjeta inválida'), ('fondos_insuficientes', 'Fondos insuficientes'), ('error_conexion', 'Error de conexión con el banco'), ('otro', 'Otro error')], max_length=50, null=True)),
                ('numero_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='application.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimos_digitos', models.CharField(max_length=4)),
                ('tipo', models.CharField(max_length=20)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta de Crédito',
                'verbose_name_plural': 'Tarjetas de Crédito',
            },
        ),
    ]
