# Generated by Django 5.2.1 on 2025-06-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_valoracionempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('suspendida', 'Suspendida'), ('reservada', 'Reservada'), ('alquilada', 'Alquilada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
