# Generated by Django 5.2 on 2025-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('politica_cancelacion', models.DecimalField(decimal_places=2, help_text='Porcentaje (%) de penalización', max_digits=5)),
                ('tipo', models.CharField(max_length=100)),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('permisos_requeridos', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_maquinas/')),
            ],
        ),
    ]
