# Generated by Django 5.2.1 on 2025-05-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='codigo',
        ),
    ]
